apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::922929370727:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1KSIBLCE2JWP0
      username: system:node:{{EC2PrivateDNSName}}
      - rolearn: arn:aws:iam::922929370727:role/UdacityFlaskDeployCBKubectlRole
        username: build
        groups:
          - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-24T03:57:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1452"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 4de5c264-a560-4f3d-a431-a96cbe895e62
